{% set name = "tangram_propkagui" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0')|int }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram
    - propka        3.1.*

about:
  home: http://github.com/insilichem/tangram_propkagui
  license: MIT
  license_family: MIT

  summary: 'UCSF Chimera extension to depict PropKa 3.1 results'

  description: |
    Analyze and depict the expected pKa values of protein residues
    with PropKa 3.1 and view them in UCSF Chimera.
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_propkagui.html
  dev_url: https://github.com/insilichem/tangram_propkagui


